version : "3"
services:
   database:
      image: postgres:latest
      container_name: database
      ports:
         - 5432:5432
      volumes:
         - pgdata:/var/lib/postgresql/data
      environment:
         POSTGRES_DB: shopping
         POSTGRES_PASSWORD: admin
         POSTGRES_USER: postgres
   backend:
      image: datvan/backend
      container_name: backend
      depends_on:
         - database
      build:
         context: .
         dockerfile: ./Dockerfile
      ports:
         - 8081:8081
volumes:
   pgdata: